# Generated by Django 5.1.4 on 2025-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='publication_attribute',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак публикации'),
        ),
    ]
