# Generated by Django 5.1.4 on 2025-02-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogentry_publication_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='quantity_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
