# Generated by Django 5.1.4 on 2025-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogentry_quantity_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='publication_attribute',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публикации'),
        ),
    ]
