# Generated by Django 5.1.4 on 2025-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogentry_publication_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Превью'),
        ),
    ]
