# Generated by Django 5.1.4 on 2025-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagery',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Изображение'),
        ),
    ]
