# Generated by Django 5.1.4 on 2025-02-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication_attribute',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публикации'),
        ),
    ]
