# Generated by Django 5.1.4 on 2025-02-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_publication_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'permissions': [('can_unpublish_product', 'can unpublish product'), ('can_delete_product', 'can delete product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
